### ISSUE TITLE
failed to install using latest jackpack

### ISSUE THREAD

**Issue by bnascimento** [jetsonhacks/installPlayStationEyeTX1#1]
I've manage to run your script and it installed the driver
lsusb also shows the camera attached
linux kernel is 3.10.96-tegra, but somehow cheese app does not show the camera feed.
any hints?
thank you

EDIT: its working as a second video device, thank you for this

**Comment by jetsonhacks** [comment]
Do you have other cameras attached?
What is the result of 
$ lsmod
$ uname -r

If you have more than one camera attached, did you select the PS3 Eye from the Cheese preferences panel?

**Comment by bnascimento** [comment]
![screenshot from 2016-10-06 08-42-48](https://cloud.githubusercontent.com/assets/3187569/19147239/c6ef1c90-8ba6-11e6-87a4-8f0c0aa2961c.png)

but appears as a second device.
best regards, thanks

EDIT: any idea where this high res video capture comes from?

**Comment by jetsonhacks** [comment]
The ov5693 is the onboard camera of the Jetson carrier board.
